  # List of carriers, where tm (transport mode) is 0 = flight; 1 = train; 2 = bus; 3 = car-sharing; 4 = ferry; 
  
  airline_carriers = [
            {"code": "RYR", "iata_code": "FR", "icao_code":"RYR", "tm": 0, "name": "Ryanair"},
            {"code": "EWG", "iata_code": "EW", "icao_code":"EWG", "tm": 0, "name": "Eurowings"},
            {"code": "GWI", "iata_code": "4U", "icao_code":"GWI", "tm": 0, "name": "Germanwings"},
            {"code": "TUI", "iata_code": "X3", "icao_code":"TUI", "tm": 0, "name": "TUIfly"},
            {"code": "BER", "iata_code": "AB", "icao_code":"BER", "tm": 0, "name": "Air Berlin"},
            {"code": "DLH", "iata_code": "LH", "icao_code":"DLH", "tm": 0, "name": "Lufthansa"},
            {"code": "CFG", "iata_code": "DE", "icao_code":"CFG", "tm": 0, "name": "Condor"},
            {"code": "GMI", "iata_code": "ST", "icao_code":"GMI", "tm": 0, "name": "Germania"},
            {"code": "GSW", "iata_code": "GM", "icao_code":"GSW", "tm": 0, "name": "Germania Flug"},
            {"code": "NLY", "iata_code": "HG", "icao_code":"NLY", "tm": 0, "name": "Niki"},
            {"code": "VLG", "iata_code": "VY", "icao_code":"VLG", "tm": 0, "name": "Vueling"},
            {"code": "IBE", "iata_code": "IB", "icao_code":"IBE", "tm": 0, "name": "Iberia"},
            {"code": "AEA", "iata_code": "UX", "icao_code":"AEA", "tm": 0, "name": "Air Europa"},
            {"code": "EZY", "iata_code": "U2", "icao_code":"EZY", "tm": 0, "name": "easyJet"},
            {"code": "EZS", "iata_code": "DS", "icao_code":"EZS", "tm": 0, "name": "easyJet Switzerland"},
            # {"code": "EJU", "iata_code": "??", "icao_code":"EJU", "tm": 0, "name": "easyJet Europe"},
            {"code": "VOE", "iata_code": "V7", "icao_code":"VOE", "tm": 0, "name": "Volotea"},
            {"code": "SAS", "iata_code": "SK", "icao_code":"SAS", "tm": 0, "name": "Scandinavian Airlines"},
            {"code": "BEL", "iata_code": "SN", "icao_code":"BEL", "tm": 0, "name": "Brussels Airlines"},
            {"code": "KLM", "iata_code": "KL", "icao_code":"KLM", "tm": 0, "name": "KLM"},
            {"code": "BAW", "iata_code": "BA", "icao_code":"BAW", "tm": 0, "name": "British Airways"},
            {"code": "AFR", "iata_code": "AF", "icao_code":"AFR", "tm": 0, "name": "Air France"},
            {"code": "PGT", "iata_code": "PC", "icao_code":"PGT", "tm": 0, "name": "Pegasus"},
            {"code": "TAP", "iata_code": "TP", "icao_code":"TAP", "tm": 0, "name": "TAP Portugal"},
            {"code": "THY", "iata_code": "TK", "icao_code":"THY", "tm": 0, "name": "Turkish Airlines"},
            {"code": "SWU", "iata_code": "LX", "icao_code":"SWU", "tm": 0, "name": "Swiss"},
            {"code": "AUA", "iata_code": "OS", "icao_code":"AUA", "tm": 0, "name": "Austrian Airlines"},
            {"code": "FIN", "iata_code": "AY", "icao_code":"FIN", "tm": 0, "name": "Finnair"},
            {"code": "SXD", "iata_code": "XG", "icao_code":"SXD", "tm": 0, "name": "SunExpress"},
            {"code": "LVL", "iata_code": "LV", "icao_code":"LVL", "tm": 0, "name": "Level"},
            {"code": "LGL", "iata_code": "LG", "icao_code":"LGL", "tm": 0, "name": "Luxair"},
            {"code": "BTI", "iata_code": "BT", "icao_code":"BTI", "tm": 0, "name": "airBaltic"},
            {"code": "WZZ", "iata_code": "W6", "icao_code":"WZZ", "tm": 0, "name": "Wizz Air"},
            {"code": "WUK", "iata_code": "W9", "icao_code":"WUK", "tm": 0, "name": "Wizz Air UK"},
            {"code": "NAX", "iata_code": "DY", "icao_code":"NAX", "tm": 0, "name": "Norwegian Air Shuttle"},
            {"code": "IBK", "iata_code": "D8", "icao_code":"IBK", "tm": 0, "name": "Norwegian"},
            {"code": "TRA", "iata_code": "HV", "icao_code":"TRA", "tm": 0, "name": "Transavia"},
            {"code": "TVF", "iata_code": "TO", "icao_code":"TVF", "tm": 0, "name": "Transavia France"},
            {"code": "IBB", "iata_code": "NT", "icao_code":"IBB", "tm": 0, "name": "Binter Canarias"},
            {"code": "RZO", "iata_code": "S4", "icao_code":"RZO", "tm": 0, "name": "Azores Airlines"},
            {"code": "SAT", "iata_code": "SP", "icao_code":"SAT", "tm": 0, "name": "SATA Air Açores"},
            {"code": "LAN", "iata_code": "LA", "icao_code":"LAN", "tm": 0, "name": "LATAM"},
            {"code": "ASL", "iata_code": "JU", "icao_code":"ASL", "tm": 0, "name": "Air Serbia"},
            {"code": "AZA", "iata_code": "AZ", "icao_code":"AZA", "tm": 0, "name": "Alitalia"},
            {"code": "ISS", "iata_code": "IG", "icao_code":"ISS", "tm": 0, "name": "Meridiana"},
            {"code": "TOS", "iata_code": "PM", "icao_code":"TOS", "tm": 0, "name": "Tropic Air"},
            {"code": "CTN", "iata_code": "OU", "icao_code":"CTN", "tm": 0, "name": "Croatia Airlines"},
            {"code": "LZB", "iata_code": "FB", "icao_code":"LZB", "tm": 0, "name": "Bulgaria Air"},
            {"code": "RNA", "iata_code": None, "icao_code": None, "tm": 0, "name": "Rhein-Neckar Air"},
            {"code": "CCM", "iata_code": "XK", "icao_code":"CCM", "tm": 0, "name": "Air Corsica"},
            {"code": "HOP", "iata_code": "A5", "icao_code":"HOP", "tm": 0, "name": "HOP!"},
            {"code": "BEE", "iata_code": "BE", "icao_code":"BEE", "tm": 0, "name": "Flybe"},
            {"code": "CLG", "iata_code": "CE", "icao_code":"CLG", "tm": 0, "name": "Chalair Aviation"},
            {"code": "TJT", "iata_code": "T7", "icao_code":"TJT", "tm": 0, "name": "Twin Jet"},
            {"code": "AUR", "iata_code": "GR", "icao_code":"AUR", "tm": 0, "name": "Aurigny"},
            {"code": "NOS", "iata_code": "NO", "icao_code":"NOS", "tm": 0, "name": "Neos"},
            {"code": "XLF", "iata_code": "SE", "icao_code":"XLF", "tm": 0, "name": "XL Airways France"},
            {"code": "TLB", "iata_code": "L5", "icao_code":"TLB", "tm": 0, "name": "Atlas Atlantique Airlines"},
            {"code": "AEE", "iata_code": "A3", "icao_code":"AEE", "tm": 0, "name": "Aegean Airlines"},
            {"code": "BMS", "iata_code": "0B", "icao_code":"BMS", "tm": 0, "name": "Blue Air"},
            {"code": "SRK", "iata_code": "SX", "icao_code":"SRK", "tm": 0, "name": "SkyWork Airlines"},
            {"code": "DWT", "iata_code": "F7", "icao_code":"DWT", "tm": 0, "name": "Etihad Regional"},
            {"code": "EIN", "iata_code": "EI", "icao_code":"EIN", "tm": 0, "name": "Aer Lingus"},
            {"code": "MGX", "iata_code": "YM", "icao_code":"MGX", "tm": 0, "name": "Montenegro Airlines"},
            {"code": "ROT", "iata_code": "RO", "icao_code":"ROT", "tm": 0, "name": "Tarom"},
            {"code": "SCO", "iata_code": "TZ", "icao_code":"SCO", "tm": 0, "name": "Scoot"},
            {"code": "LLC", "iata_code": "S5", "icao_code":"LLC", "tm": 0, "name": "Small Planet Airlines"},
            {"code": "NGT", "iata_code": "RM", "icao_code":"NGT", "tm": 0, "name": "Armenia Aircompany"},
            {"code": "CSA", "iata_code": "OK", "icao_code":"CSA", "tm": 0, "name": "Czech Airlines"},
            {"code": "AWC", "iata_code": "ZT", "icao_code":"AWC", "tm": 0, "name": "Titan Airways"},
            {"code": "BRU", "iata_code": "B2", "icao_code":"BRU", "tm": 0, "name": "Belavia"},
            {"code": "WJA", "iata_code": "WS", "icao_code":"WJA", "tm": 0, "name": "WestJet"},
            {"code": "DTH", "iata_code": "SF", "icao_code":"DTH", "tm": 0, "name": "Tassili Airlines"},
            {"code": "AUL", "iata_code": "5N", "icao_code":"AUL", "tm": 0, "name": "Nordavia"},
            {"code": "KZR", "iata_code": "KC", "icao_code":"KZR", "tm": 0, "name": "Air Astana"},
            {"code": "EVE", "iata_code": "E9", "icao_code":"EVE", "tm": 0, "name": "Evelop!"},
            {"code": "LDM", "iata_code": "OE", "icao_code":"LDM", "tm": 0, "name": "Laudamotion"},
            {"code": "ALD", "iata_code": "AL", "icao_code":"ALD", "tm": 0, "name": "Air Leisure"},
            {"code": "LLX", "iata_code": "5P", "icao_code": "LLX", "tm": 0, "name": "Small Planet Airlines (Germany)"},
            # {"code": None, "iata_code": None, "icao_code": None, "tm": 0, "name": "Melilla Airlines"},
            {"code": "LOG", "iata_code": "LM", "icao_code": "LOG", "tm": 0, "name": "Loganair"},
            {"code": "AAL", "iata_code": "AA", "icao_code": "AAL", "tm": 0, "name": "American Airlines"},
            {"code": "ABG", "iata_code": "RL", "icao_code": "ABG", "tm": 0, "name": "Royal Flight"},
            {"code": "SLD", "iata_code": None, "icao_code": "SLD", "tm": 0, "name": "Silver Air"},
            {"code": "RBA", "iata_code": "BI", "icao_code": "RBA", "tm": 0, "name": "Royal Brunei Airlines"},
            {"code": "CSC", "iata_code": "3U", "icao_code": "CSC", "tm": 0, "name": "Sichuan Airlines"},
            {"code": "ADR", "iata_code": "JP", "icao_code": "ADR", "tm": 0, "name": "Adria Airways"},
            {"code": "HVN", "iata_code": "VN", "icao_code": "HVN", "tm": 0, "name": "Vietnam Airlines"},
            {"code": "MEV", "iata_code": "VL", "icao_code": "MEV", "tm": 0, "name": "Med-View Airline"},
            {"code": "CAT", "iata_code": None, "icao_code": "CAT", "tm": 0, "name": "Copenhagen Air Taxi"},
            {"code": "BMR", "iata_code": "BM", "icao_code": "BMR", "tm": 0, "name": "BMI Regional"},
            {"code": "PNX", "iata_code": "IS", "icao_code": "PNX", "tm": 0, "name": "AIS Airlines"},
            {"code": "RAM", "iata_code": "AT", "icao_code": "RAM", "tm": 0, "name": "Royal Air Maroc"},
            {"code": "VKG", "iata_code": "DK", "icao_code": "VKG", "tm": 0, "name": "Thomas Cook Scandinavia"},
            {"code": "BRX", "iata_code": "DC", "icao_code": "BRX", "tm": 0, "name": "Braathens Regional Airways"},
            {"code": "SCW", "iata_code": "TF", "icao_code": "SCW", "tm": 0, "name": "Braathens Regional Aviation"},
            # {"code": None, "iata_code": None, "icao_code": None, "tm": 0, "name": "Sparrow Aviation"},
            {"code": "LAV", "iata_code": "AP", "icao_code": "LAV", "tm": 0, "name": "AlbaStar"},
            {"code": "CYF", "iata_code": "U8", "icao_code": "CYF", "tm": 0, "name": "Tus Air"},
            {"code": "KTK", "iata_code": "ZF", "icao_code": "KTK", "tm": 0, "name": "Azur Air"},
            {"code": "FEI", "iata_code": None, "icao_code": "FEI", "tm": 0, "name": "Eagle Air"},
            {"code": "IBS", "iata_code": "I2", "icao_code": "IBS", "tm": 0, "name": "Iberia Express"},
            {"code": "AAR", "iata_code": "OZ", "icao_code": "AAR", "tm": 0, "name": "Asiana Airlines"},
            {"code": "SDR", "iata_code": "SR", "icao_code": "SDR", "tm": 0, "name": "Sundair"},
            {"code": "SWT", "iata_code": "WT", "icao_code": "SWT", "tm": 0, "name": "Swiftair"},
            {"code": "PRI", "iata_code": "PF", "icao_code": "PRI", "tm": 0, "name": "Primera Air Nordic"},
            {"code": "PRW", "iata_code": "6F", "icao_code": "PRW", "tm": 0, "name": "Primera Air"},
            {"code": "HGH", "iata_code": None, "icao_code": "HGH", "tm": 0, "name": "Atlantic Air Lift"},
            {"code": "ANA", "iata_code": "NH", "icao_code": "ANA", "tm": 0, "name": "All Nippon Airways"},
            {"code": "MGL", "iata_code": "OM", "icao_code": "MGL", "tm": 0, "name": "MIAT Mongolian Airlines"},
            {"code": "TWI", "iata_code": "TI", "icao_code": "TWI", "tm": 0, "name": "Tailwind Airlines"},
            {"code": "TGZ", "iata_code": "A9", "icao_code": "TGZ", "tm": 0, "name": "Georgian Airways"},
            {"code": "CES", "iata_code": "MU", "icao_code": "CES", "tm": 0, "name": "China Eastern Airlines"},
            {"code": "SEH", "iata_code": "GQ", "icao_code": "SEH", "tm": 0, "name": "Sky Express (Greece)"},
            {"code": "CVE", "iata_code": None, "icao_code": "CVE", "tm": 0, "name": "Cabo Verde Express"},
            {"code": "JAL", "iata_code": "JL", "icao_code": "JAL", "tm": 0, "name": "Japan Airlines"},
            {"code": "WIF", "iata_code": "WF", "icao_code": "WIF", "tm": 0, "name": "Widerøe"},
            {"code": "ALK", "iata_code": "UL", "icao_code": "ALK", "tm": 0, "name": "SriLankan Airlines"},
            {"code": "RWD", "iata_code": "WB", "icao_code": "RWD", "tm": 0, "name": "RwandAir"},
            {"code": "CCA", "iata_code": "CA", "icao_code": "CCA", "tm": 0, "name": "Air China"},
            {"code": "EDW", "iata_code": "WK", "icao_code": "EDW", "tm": 0, "name": "Edelweiss Air"},
            {"code": "ELY", "iata_code": "LY", "icao_code": "ELY", "tm": 0, "name": "El Al"},
            {"code": "MSR", "iata_code": "MS", "icao_code": "MSR", "tm": 0, "name": "Egypt Air"},
            {"code": "ENT", "iata_code": "E4", "icao_code": "ENT", "tm": 0, "name": "Enter Air"},
            {"code": "KAC", "iata_code": "KU", "icao_code": "KAC", "tm": 0, "name": "Kuwait Airways"},
            # {"code": None, "iata_code": None, "icao_code": None, "tm": 0, "name": "Clicandfly.com"},
            # {"code":  None, "iata_code": None, "icao_code": None, "tm": 0, "name": "Transun"},
            {"code": "CND", "iata_code": "CD", "icao_code": "CND", "tm": 0, "name": "Corendon Dutch"},
            {"code": "BLX", "iata_code": "6B", "icao_code": "BLX", "tm": 0, "name": "TUIfly Nordic"},
            {"code": "TCX", "iata_code": "MT", "icao_code": "TCX", "tm": 0, "name": "Thomas Cook Airlines"},
            {"code": "ATV", "iata_code": None, "icao_code": "ATV", "tm": 0, "name": "Avanti Air"},
            {"code": "PIA", "iata_code": "PK", "icao_code": "PIA", "tm": 0, "name": "Pakistan Int. Airlines"},
            {"code": "AIZ", "iata_code": "IZ", "icao_code": "AIZ", "tm": 0, "name": "Arkia"},
            {"code": "NVR", "iata_code": "N9", "icao_code": "NVR", "tm": 0, "name": "Novair"},
            {"code": "ICE", "iata_code": "FI", "icao_code": "ICE", "tm": 0, "name": "Icelandair"},
            {"code": "FIA", "iata_code": "5F", "icao_code": "FIA", "tm": 0, "name": "FlyOne"},
            {"code": "VIM", "iata_code": "VL", "icao_code": "VIM", "tm": 0, "name": "Air VIA"},
            {"code": "KKK", "iata_code": "KK", "icao_code": "KKK", "tm": 0, "name": "AtlasGlobal"},
            {"code": "VIR", "iata_code": "VS", "icao_code": "VIR", "tm": 0, "name": "Virgin Atlantic"},
            {"code": "EXS", "iata_code": "LS", "icao_code": "EXS", "tm": 0, "name": "Jet2.com"},
            {"code": "FDB", "iata_code": "FZ", "icao_code": "FDB", "tm": 0, "name": "FlyDubai"},
            {"code": "LLM", "iata_code": "YC", "icao_code": "LLM", "tm": 0, "name": "Yamal Airlines"},
            {"code": "MON", "iata_code": "ZB", "icao_code": "MON", "tm": 0, "name": "Monarch Airlines"},
            {"code": "RSY", "iata_code": "I4", "icao_code": "RSY", "tm": 0, "name": "I-Fly"},
            {"code": "ART", "iata_code": "6Y", "icao_code": "ART", "tm": 0, "name": "SmartLynx"},
            {"code": "PBD", "iata_code": "DP", "icao_code": "PBD", "tm": 0, "name": "Pobeda"},
            {"code": "JAI", "iata_code": "9W", "icao_code": "JAI", "tm": 0, "name": "Jet Airways"},
            {"code": "NMB", "iata_code": "SW", "icao_code": "NMB", "tm": 0, "name": "Air Namibia"},
            {"code": "PAL", "iata_code": "PR", "icao_code": "PAL", "tm": 0, "name": "Philippine Airlines"},
            {"code": "WOW", "iata_code": "WW", "icao_code": "WOW", "tm": 0, "name": "WOW Air"},
            {"code": "IRM", "iata_code": "W5", "icao_code": "IRM", "tm": 0, "name": "Mahan Air"},
            {"code": "SOV", "iata_code": "6W", "icao_code": "SOV", "tm": 0, "name": "Saratov Airlines"},
            {"code": "TVP", "iata_code": "3Z", "icao_code": "TVP", "tm": 0, "name": "Travel Service Polska"},
            {"code": "TDR", "iata_code": "C3", "icao_code": "TDR", "tm": 0, "name": "Trade Air"},
            {"code": "MEA", "iata_code": "ME", "icao_code": "MEA", "tm": 0, "name": "Middle East Airlines"},
            {"code": "WRC", "iata_code": "7W", "icao_code": "WRC", "tm": 0, "name": "Windrose Airlines"},
            {"code": "BGH", "iata_code": "8H", "icao_code": "BGH", "tm": 0, "name": "BH Air"},
            {"code": "AVA", "iata_code": "AV", "icao_code": "AVA", "tm": 0, "name": "Avianca"},
            {"code": "IOS", "iata_code": None, "icao_code": "IOS", "tm": 0, "name": "Isles of Scilly Skybus"},
            {"code": "AWU", "iata_code": "7E", "icao_code": "AWU", "tm": 0, "name": "Sylt Air"},
            {"code": "CLW", "iata_code": None, "icao_code": "CLW", "tm": 0, "name": "LOT Charters"},
            {"code": "TCV", "iata_code": "VR", "icao_code": "TCV", "tm": 0, "name": "TACV"},
            {"code": "DAL", "iata_code": "DL", "icao_code": "DAL", "tm": 0, "name": "Delta Air Lines"},
            {"code": "PEV", "iata_code": "PE", "icao_code": "PEV", "tm": 0, "name": "People's Viennaline"},
            # {"code": None, "iata_code": None, "icao_code": None, "tm": 0, "name": "jetXtra.com"},
            {"code": "RJA", "iata_code": "RJ", "icao_code": "RJA", "tm": 0, "name": "Royal Jordanian"},
            {"code": "GIA", "iata_code": "GA", "icao_code": "GIA", "tm": 0, "name": "Garuda Indonesia"},
            {"code": "AUI", "iata_code": "PS", "icao_code": "AUI", "tm": 0, "name": "Ukraine Int. Airlines"},
            {"code": "ELB", "iata_code": "EL", "icao_code": "ELB", "tm": 0, "name": "Ellinair"},
            # {"code": None, "iata_code": None, "icao_code": None, "tm": 0, "name": "Aer Arann Islands"},
            # {"code":  None, "iata_code": None, "icao_code": None, "tm": 0, "name": "Jet Time"},
            {"code": "MAC", "iata_code": "3O", "icao_code": "MAC", "tm": 0, "name": "Air Arabia Maroc"},
            {"code": "SBI", "iata_code": "S7", "icao_code": "SBI", "tm": 0, "name": "S7 Airlines"},
            {"code": "SDM", "iata_code": "FV", "icao_code": "SDM", "tm": 0, "name": "Rossiya Airlines"},
            {"code": "CAI", "iata_code": "XC", "icao_code": "CAI", "tm": 0, "name": "Corendon Airlines"},
            {"code": "CXI", "iata_code": "XR", "icao_code": "CXI", "tm": 0, "name": "Corendon Airlines Europe"},
            {"code": "MYA", "iata_code": None, "icao_code": "MYA", "tm": 0, "name": "Mýflug"},
            {"code": "MSA", "iata_code": "M4", "icao_code": "MSA", "tm": 0, "name": "Mistral Air"},
            {"code": "BGT", "iata_code": None, "icao_code": "BGT", "tm": 0, "name": "Bergen Air Transport"},
            {"code": "AFL", "iata_code": "SU", "icao_code": "AFL", "tm": 0, "name": "Aeroflot"},
            {"code": "QTR", "iata_code": "QR", "icao_code": "QTR", "tm": 0, "name": "Qatar Airways"},
            {"code": "SWR", "iata_code": "LX", "icao_code": "SWR", "tm": 0, "name": "Swiss Int. Air Lines"},
            {"code": "NWS", "iata_code": "N4", "icao_code": "NWS", "tm": 0, "name": "Nordwind Airlines"},
            {"code": "TYA", "iata_code": "Y7", "icao_code": "TYA", "tm": 0, "name": "NordStar"},
            {"code": "CSN", "iata_code": "CZ", "icao_code": "CSN", "tm": 0, "name": "China Southern Airlines"},
            {"code": "PLM", "iata_code": "EB", "icao_code": "PLM", "tm": 0, "name": "Wamos Air"},
            {"code": "OAL", "iata_code": "OA", "icao_code": "OAL", "tm": 0, "name": "Olympic Air"},
            {"code": "GCR", "iata_code": "GS", "icao_code": "GCR", "tm": 0, "name": "Tianjin Airlines"},
            {"code": "SLM", "iata_code": "PY", "icao_code": "SLM", "tm": 0, "name": "Surinam Airways"},
            {"code": "LYD", "iata_code": None, "icao_code": "LYD", "tm": 0, "name": "LyddAir"},
            {"code": "BBC", "iata_code": "BG", "icao_code": "BBC", "tm": 0, "name": "Biman Bangladesh Airlines"},
            {"code": "TAM", "iata_code": "JJ", "icao_code": "TAM", "tm": 0, "name": "LATAM Brasil"},
            # {"code": None, "iata_code": None, "icao_code": None, "tm": 0, "name": "OFD Ostfriesischer-Flug-Dienst"},
            {"code": "FPO", "iata_code": "5O", "icao_code": "FPO", "tm": 0, "name": "ASL Airlines France"},
            {"code": "FEG", "iata_code": "FT", "icao_code": "FEG", "tm": 0, "name": "FlyEgypt"},
            {"code": "SWG", "iata_code": "WG", "icao_code": "SWG", "tm": 0, "name": "Sunwing Airlines"},
            {"code": "KRP", "iata_code": "V3", "icao_code": "KRP", "tm": 0, "name": "Carpatair"},
            {"code": "MAS", "iata_code": "MH", "icao_code": "MAS", "tm": 0, "name": "Malaysia Airlines"},
            {"code": "SYL", "iata_code": "R3", "icao_code": "SYL", "tm": 0, "name": "Yakutia Airlines"},
            {"code": "IGA", "iata_code": "TE", "icao_code": "IGA", "tm": 0, "name": "Skytaxi"},
            {"code": "IRA", "iata_code": "IR", "icao_code": "IRA", "tm": 0, "name": "Iran Air"},
            {"code": "AIC", "iata_code": "AI", "icao_code": "AIC", "tm": 0, "name": "Air India"},
            {"code": "OBS", "iata_code": "6O", "icao_code": "OBS", "tm": 0, "name": "Orbest"},
            {"code": "AAF", "iata_code": "ZI", "icao_code": "AAF", "tm": 0, "name": "Aigle Azur"},
            {"code": "NTJ", "iata_code": "2N", "icao_code": "NTJ", "tm": 0, "name": "NextJet"},
            {"code": "TVL", "iata_code": "7O", "icao_code": "TVL", "tm": 0, "name": "Travel Service Hungary"},
            {"code": "EVA", "iata_code": "BR", "icao_code": "EVA", "tm": 0, "name": "EVA Air"},
            {"code": "JAF", "iata_code": "TB", "icao_code": "JAF", "tm": 0, "name": "TUIfly Belgium"},
            {"code": "ETH", "iata_code": "ET", "icao_code": "ETH", "tm": 0, "name": "Ethiopian Airlines"},
            {"code": "ROU", "iata_code": "RV", "icao_code": "ROU", "tm": 0, "name": "Air Canada Rouge"},
            {"code": "SUS", "iata_code": "EZ", "icao_code": "SUS", "tm": 0, "name": "Sun Air of Scandinavia"},
            {"code": "ACA", "iata_code": "AC", "icao_code": "ACA", "tm": 0, "name": "Air Canada"},
            {"code": "BUR", "iata_code": "B1", "icao_code": "BUR", "tm": 0, "name": "Air Bucharest"},
            {"code": "WLB", "iata_code": "W7", "icao_code": "WLB", "tm": 0, "name": "Wings of Lebanon"},
            {"code": "GFA", "iata_code": "GF", "icao_code": "GFA", "tm": 0, "name": "Gulf Air"},
            {"code": "GLP", "iata_code": "GH", "icao_code": "GLP", "tm": 0, "name": "Globus Airlines"},
            {"code": "TAR", "iata_code": "TU", "icao_code": "TAR", "tm": 0, "name": "Tunisair"},
            {"code": "GRL", "iata_code": "GL", "icao_code": "GRL", "tm": 0, "name": "Air Greenland"},
            {"code": "CAL", "iata_code": "CI", "icao_code": "CAL", "tm": 0, "name": "China Airlines"},
            {"code": "MAU", "iata_code": "MK", "icao_code": "MAU", "tm": 0, "name": "Air Mauritius"},
            {"code": "UAE", "iata_code": "EK", "icao_code": "UAE", "tm": 0, "name": "Emirates"},
            {"code": "OAS", "iata_code": "WY", "icao_code": "OAS", "tm": 0, "name": "Oman Air"},
            {"code": "WIA", "iata_code": "WM", "icao_code": "WIA", "tm": 0, "name": "Winair"},
            {"code": "LTR", "iata_code": "L5", "icao_code": "LTR", "tm": 0, "name": "Lufttransport"},
            {"code": "TVQ", "iata_code": "6D", "icao_code": "TVQ", "tm": 0, "name": "Travel Service Slovakia"},
            {"code": "CHH", "iata_code": "HU", "icao_code": "CHH", "tm": 0, "name": "Hainan Airlines"},
            {"code": "BPS", "iata_code": None, "icao_code": "BPS", "tm": 0, "name": "Budapest Aircraft Service"},
            {"code": "NFA", "iata_code": "M3", "icao_code": "NFA", "tm": 0, "name": "Air Norway"},
            {"code": "THA", "iata_code": "TG", "icao_code": "THA", "tm": 0, "name": "Thai Airways"},
            {"code": "BPA", "iata_code": "BV", "icao_code": "BPA", "tm": 0, "name": "Blue Panorama"},
            {"code": "KQA", "iata_code": "KQ", "icao_code": "KQA", "tm": 0, "name": "Kenya Airways"},
            {"code": "SRN", "iata_code": "P8", "icao_code": "SRN", "tm": 0, "name": "Sprint Air"},
            {"code": "MLD", "iata_code": "9U", "icao_code": "MLD", "tm": 0, "name": "Air Moldova"},
            {"code": "AMC", "iata_code": "KM", "icao_code": "AMC", "tm": 0, "name": "Air Malta"},
            {"code": "BBG", "iata_code": "BZ", "icao_code": "BBG", "tm": 0, "name": "BlueBird Airways"},
            # {"code": None, "iata_code": None, "icao_code": None, "tm": 0, "name": "Scandjet"},
            {"code": "MSC", "iata_code": "SM", "icao_code": "MSC", "tm": 0, "name": "Air Cairo"},
            {"code": "EVJ", "iata_code": None, "icao_code": "EVJ", "tm": 0, "name": "Everjets"},
            {"code": None, "iata_code": None, "icao_code": None, "tm": 0, "name": "Windward Express"},
            {"code": "CXA", "iata_code": "MF", "icao_code": "CXA", "tm": 0, "name": "XiamenAir"},
            {"code": "QFA", "iata_code": "QF", "icao_code": "QFA", "tm": 0, "name": "Qantas"},
            {"code": "NWG", "iata_code": None, "icao_code": "NWG", "tm": 0, "name": "Airwing"},
            {"code": "DLA", "iata_code": "EN", "icao_code": "DLA", "tm": 0, "name": "Air Dolomiti"},
            {"code": "IAW", "iata_code": "IA", "icao_code": "IAW", "tm": 0, "name": "Iraqi Airways"},
            {"code": "OHY", "iata_code": "8Q", "icao_code": "OHY", "tm": 0, "name": "Onur Air"},
            {"code": "SXS", "iata_code": "XQ", "icao_code": "SXS", "tm": 0, "name": "SunExpress"},
            {"code": "TVS", "iata_code": "QS", "icao_code": "TVS", "tm": 0, "name": "SmartWings"},
            {"code": "DTR", "iata_code": "DX", "icao_code": "DTR", "tm": 0, "name": "Danish Air Transport"},
            {"code": "EZE", "iata_code": "T3", "icao_code": "EZE", "tm": 0, "name": "Eastern Airways"},
            {"code": "TSC", "iata_code": "TS", "icao_code": "TSC", "tm": 0, "name": "Air Transat"},
            {"code": "FCB", "iata_code": "CO", "icao_code": "FCB", "tm": 0, "name": "Cobalt Air"},
            {"code": "SAA", "iata_code": "SA", "icao_code": "SAA", "tm": 0, "name": "South African Airways"},
            {"code": "AWT", "iata_code": "2B", "icao_code": "AWT", "tm": 0, "name": "Albawings"},
            {"code": "ABR", "iata_code": "AG", "icao_code": "ABR", "tm": 0, "name": "ASL Airlines Ireland"},
            {"code": "TCW", "iata_code": "HQ", "icao_code": "TCW", "tm": 0, "name": "Thomas Cook Airlines Belgium"},
            {"code": "SMR", "iata_code": "SZ", "icao_code": "SMR", "tm": 0, "name": "Somon Air"},
            {"code": "OAW", "iata_code": "2L", "icao_code": "OAW", "tm": 0, "name": "Helvetic Airways"},
            {"code": "CNF", "iata_code": "PM", "icao_code": "CNF", "tm": 0, "name": "CanaryFly"},
            {"code": "BUC", "iata_code": "H6", "icao_code": "BUC", "tm": 0, "name": "Bulgarian Air Charter"},
            {"code": "SVA", "iata_code": "SV", "icao_code": "SVA", "tm": 0, "name": "Saudia"},
            {"code": "SXR", "iata_code": "XW", "icao_code": "SXR", "tm": 0, "name": "Sky Express"},
            {"code": "TOM", "iata_code": "BY", "icao_code": "TOM", "tm": 0, "name": "Thomson Airways"},
            {"code": "TFL", "iata_code": "OR", "icao_code": "TFL", "tm": 0, "name": "TUI fly Netherlands"},
            {"code": "BCY", "iata_code": "WX", "icao_code": "BCY", "tm": 0, "name": "CityJet"},
            {"code": "SUV", "iata_code": None, "icao_code": "SUV", "tm": 0, "name": "Sundance Air Venezuela"},
            {"code": "BAY", "iata_code": None, "icao_code": "BAY", "tm": 0, "name": "Bravo Airways"},
            {"code": "ISR", "iata_code": "6H", "icao_code": "ISR", "tm": 0, "name": "Israir"},
            {"code": "UTA", "iata_code": "UT", "icao_code": "UTA", "tm": 0, "name": "UTair"},
            {"code": "TUA", "iata_code": "T5", "icao_code": "TUA", "tm": 0, "name": "Turkmenistan Airlines"},
            # {"code": "RVP", "iata_code": "WV", "icao_code": "RVP", "tm": 0, "name": "Aero VIP Portugal"},
            {"code": "CPA", "iata_code": "CX", "icao_code": "CPA", "tm": 0, "name": "Cathay Pacific"},
            {"code": "SIA", "iata_code": "SQ", "icao_code": "SIA", "tm": 0, "name": "Singapore Airlines"},
            {"code": "BGM", "iata_code": "2B", "icao_code": "BGM", "tm": 0, "name": "Ak Bars Aero"},
            {"code": "FVK", "iata_code": "VF", "icao_code": "FVK", "tm": 0, "name": "FlyViking"},
            {"code": "DAT", "iata_code": "D4", "icao_code": "DAT", "tm": 0, "name": "DART Ukrainian Airlines"},
            {"code": "FHY", "iata_code": "FH", "icao_code": "FHY", "tm": 0, "name": "Freebird Airlines"},
            {"code": "SVR", "iata_code": "U6", "icao_code": "SVR", "tm": 0, "name": "Ural Airlines"},
            {"code": "DAH", "iata_code": "AH", "icao_code": "DAH", "tm": 0, "name": "Air Algerie"},
            {"code": "STK", "iata_code": "EI", "icao_code": "STK", "tm": 0, "name": "Aer Lingus Regional"},
            # {"code": None, "iata_code": None, "icao_code": None, "tm": 0, "name": "Hebridean Air Services"},
            {"code": "DVR", "iata_code": "DI", "icao_code": "DVR", "tm": 0, "name": "Divi Divi Air"},
            {"code": "RLU", "iata_code": "7R", "icao_code": "RLU", "tm": 0, "name": "RusLine"},
            {"code": "AZI", "iata_code": "A2", "icao_code": "AZI", "tm": 0, "name": "Astra Airlines"},
            {"code": "FLI", "iata_code": "RC", "icao_code": "FLI", "tm": 0, "name": "Atlantic Airways"},
            {"code": "ARZ", "iata_code": None, "icao_code": "ARZ", "tm": 0, "name": "Azur Air (Germany)"},
            {"code": "MMD", "iata_code": "6I", "icao_code": "MMD", "tm": 0, "name": "Air Alsie"},
            {"code": "UAL", "iata_code": "UA", "icao_code": "UAL", "tm": 0, "name": "United Airlines"},
            {"code": "LLP", "iata_code": "P7", "icao_code": "LLP", "tm": 0, "name": "Small Planet Airlines Poland"},
            {"code": "CYP", "iata_code": "CY", "icao_code": "CYP", "tm": 0, "name": "Cyprus Airways"},
            {"code": "ETD", "iata_code": "EY", "icao_code": "ETD", "tm": 0, "name": "Etihad Airways"},
            {"code": "AMX", "iata_code": "AM", "icao_code": "AMX", "tm": 0, "name": "Aeroméxico"},
            {"code": "INC", "iata_code": "7I", "icao_code": "INC", "tm": 0, "name": "Insel Air."},
            {"code": "NLU", "iata_code": "8I", "icao_code": "NLU", "tm": 0, "name": "Insel Air"},
            # {"code":  None, "iata_code": None, "icao_code":  None, "tm": 0, "name": "Jonair"},
            {"code": "FXI", "iata_code": "NY", "icao_code": "FXI", "tm": 0, "name": "Air Iceland Connect"},
            {"code": "UZB", "iata_code": "HY", "icao_code": "UZB", "tm": 0, "name": "Uzbekistan Airways"},
            {"code": "LOT", "iata_code": "LO", "icao_code": "LOT", "tm": 0, "name": "LOT Polish Airlines"},
            {"code": "ANZ", "iata_code": "NZ", "icao_code": "ANZ", "tm": 0, "name": "Air New Zealand"},
            {"code": "HHN", "iata_code": "HR", "icao_code": "HHN", "tm": 0, "name": "Hahn Air"},
            {"code": "KAL", "iata_code": "KE", "icao_code": "KAL", "tm": 0, "name": "Korean Air"},
            {"code": "HSV", "iata_code": None, "icao_code": "HSV", "tm": 0, "name": "Direktflyg"},
            {"code": "LBT", "iata_code": "BJ", "icao_code": "LBT", "tm": 0, "name": "Nouvelair"},
            {"code": "MOV", "iata_code": "NN", "icao_code": "MOV", "tm": 0, "name": "VIM Airlines"},
            {"code": "WLM", "iata_code": "VO", "icao_code": "WLM", "tm": 0, "name": "VLM Airlines Slovenia"},
            {"code": "CRL", "iata_code": "SS", "icao_code": "CRL", "tm": 0, "name": "Corsair International"},

            # {"code": None, "iata_code": None, "icao_code": None, "tm": 0, "name": "Heli Air"},
            {"code": "UDN", "iata_code": "Z6", "icao_code": "UDN", "tm": 0, "name": "Dniproavia"},
            {"code": "LMU", "iata_code": "UJ", "icao_code": "LMU", "tm": 0, "name": "AlMasria Universal Airlines"},
            {"code": "MDM", "iata_code": "JB", "icao_code": "MDM", "tm": 0, "name": "Medavia"},
            {"code": "ABY", "iata_code": "G9", "icao_code": "ABY", "tm": 0, "name": "Air Arabia"},
            {"code": "RWZ", "iata_code": "WZ", "icao_code": "RWZ", "tm": 0, "name": "Red Wings Airlines"},
            {"code": "TBM", "iata_code": "HH", "icao_code": "TBM", "tm": 0, "name": "Taban Air"},
            {"code": "ERN", "iata_code": "EG", "icao_code": "ERN", "tm": 0, "name": "Ernest Airlines"},
            {"code": "TUX", "iata_code": "UG", "icao_code": "TUX", "tm": 0, "name": "Tunisair Express"},
            {"code": "BUG", "iata_code": "RT", "icao_code": "BUG", "tm": 0, "name": "UVT Aero"},
            {"code": "UTN", "iata_code": "QU", "icao_code": "UTN", "tm": 0, "name": "Azur Air Ukraine"},
            {"code": "UJX", "iata_code": "UH", "icao_code": "UJX", "tm": 0, "name": "AtlasGlobal Ukraine"},
            {"code": "IRQ", "iata_code": "QB", "icao_code": "IRQ", "tm": 0, "name": "Qeshm Airlines"},
            {"code": "KAR", "iata_code": "IK", "icao_code": "KAR", "tm": 0, "name": "Pegas Fly"},
            {"code": "MYX", "iata_code": None, "icao_code": "MYX", "tm": 0, "name": "Smartlynx Airlines Estonia"},
            {"code": "MSI", "iata_code": "M9", "icao_code": "MSI", "tm": 0, "name": "Motor Sich Airlines"},
            {"code": "UKM", "iata_code": "UF", "icao_code": "UKM", "tm": 0, "name": "UM Airlines"},
            # {"code": None, "iata_code": None, "icao_code": None, "tm": 0, "name": "Scandjet"},
            {"code": "IZA", "iata_code": "I8", "icao_code": "IZA", "tm": 0, "name": "Izhavia"},
            {"code": "SSV", "iata_code": "5G", "icao_code": "SSV", "tm": 0, "name": "Anda Air"},
            {"code": "ANR", "iata_code": "YE", "icao_code": "ANR", "tm": 0, "name": "Yanair"},
            {"code": "PWF", "iata_code": "8W", "icao_code": "PWF", "tm": 0, "name": "Private Wings"},
            # {"code":  None, "iata_code": None, "icao_code": None, "tm": 0, "name": "Hebridean Air Services"},
            {"code": "SYA", "iata_code": "FS", "icao_code": "SYA", "tm": 0, "name": "Syphax Airlines"},
            {"code": "KSM", "iata_code": None, "icao_code": "KSM", "tm": 0, "name": "Kosmos Airlines"},
            {"code": "NSS", "iata_code": "NA", "icao_code": "NSS", "tm": 0, "name": "Nesma Airlines"},
            {"code": "RIV", "iata_code": "GP", "icao_code": "RIV", "tm": 0, "name": "APG Airlines"},
            {"code": "FXT", "iata_code": "W2", "icao_code": "FXT", "tm": 0, "name": "Flexflight"},
            {"code": "PUE", "iata_code": "PU", "icao_code": "PUE", "tm": 0, "name": "Plus Ultra Lineas Aereas"},
            {"code": "REU", "iata_code": "UU", "icao_code": "REU", "tm": 0, "name": "Air Austral"},
            {"code": "ANE", "iata_code": "YW", "icao_code": "ANE", "tm": 0, "name": "Air Nostrum"},
            {"code": "WHT", "iata_code": "WI", "icao_code": "WHT", "tm": 0, "name": "White Airways"},
            {"code": "MXD", "iata_code": "OD", "icao_code": "MXD", "tm": 0, "name": "Malindo Air"},
            {"code": "AHY", "iata_code": "J2", "icao_code": "AHY", "tm": 0, "name": "Azerbaijan Airlines"},
            {"code": "MUT", "iata_code": "A4", "icao_code": "MUT", "tm": 0, "name": "Azimuth"},
            {"code": "CBJ", "iata_code": "JD", "icao_code": "CBJ", "tm": 0, "name": "Beijing Capital"},
            {"code": "ANP", "iata_code": "VK", "icao_code": "ANP", "tm": 0, "name": "Air Nigeria"},

            {"code": "CFX", "iata_code": "CF", "icao_code":  None, "tm": 0, "name": "City Airline"},
            {"code": "H1X", "iata_code": "H1", "icao_code":  None, "tm": 0, "name": "Hahn Air Systems"},

            #unknown
            {"code": "XXX", "iata_code": None, "icao_code":  None, "tm": 0, "name": ""},
        ]

        train_carriers = [
            #International
            {"code": "tACC", "iata_code": '9B', "icao_code": None, "tm": 1, "name": "AccesRail"},
            {"code": "tTLY", "iata_code": '2H', "icao_code": None, "tm": 1, "name": "Thalys"},
            {"code": "tEUR", "iata_code": '9F', "icao_code": None, "tm": 1, "name": "Eurostar"},
            {"code": "tGRL", "iata_code": '9G', "icao_code": None, "tm": 1, "name": "9G Rail"},
            {"code": "tIZY", "iata_code": None, "icao_code": None, "tm": 1, "name": "IZY"},

            #AT
            {"code": "tOBB", "iata_code": None, "icao_code": None, "tm": 1, "name": "ÖBB"},


            #BE
            {"code": "tBNE", "iata_code": None, "icao_code": None, "tm": 1, "name": "NMBS Europe"},
            {"code": "tBEL", "iata_code": None, "icao_code": None, "tm": 1, "name": "SNCB/NMBS"},

            #BY
            {"code": "tBLR", "iata_code": None, "icao_code": None, "tm": 1, "name": "Belarusian Railway"},

            #CH
            {"code": "tSBB", "iata_code": None, "icao_code": None, "tm": 1, "name": "SBB"},
            {"code": "tRHB", "iata_code": None, "icao_code": None, "tm": 1, "name": "Rhätische Bahn"},

            #CZ
            {"code": "tCZR", "iata_code": None, "icao_code": None, "tm": 1, "name": "ČD"},
            {"code": "tLEO", "iata_code": None, "icao_code": None, "tm": 1, "name": "Leo Express"},
            {"code": "tRJT", "iata_code": None, "icao_code": None, "tm": 1, "name": "RegioJet"},

            #DE
            {"code": "tABL", "iata_code": None, "icao_code": None, "tm": 1, "name": "Abellio"},
            {"code": "tAGI", "iata_code": None, "icao_code": None, "tm": 1, "name": "Agilis"},
            {"code": "tALX", "iata_code": None, "icao_code": None, "tm": 1, "name": "alex"},
            {"code": "tALE", "iata_code": None, "icao_code": None, "tm": 1, "name": "Alleo"}, #Cooperation DB and SNCF
            {"code": "tBAY", "iata_code": None, "icao_code": None, "tm": 1, "name": "Bayerische Regiobahn"},
            {"code": "tDBA", "iata_code": '2A', "icao_code": None, "tm": 1, "name": "Deutsche Bahn"},
            {"code": "tENO", "iata_code": None, "icao_code": None, "tm": 1, "name": "enno"},
            {"code": "tERX", "iata_code": None, "icao_code": None, "tm": 1, "name": "erixx"},
            {"code": "tEVB", "iata_code": None, "icao_code": None, "tm": 1, "name": "evb"},
            {"code": "tFLX", "iata_code": None, "icao_code": None, "tm": 1, "name": "FlixTrain"},
            {"code": "tHKX", "iata_code": None, "icao_code": None, "tm": 1, "name": "HKX"},
            {"code": "tLOC", "iata_code": None, "icao_code": None, "tm": 1, "name": "Locomore"},
            {"code": "tMRD", "iata_code": None, "icao_code": None, "tm": 1, "name": "Meridian"},
            {"code": "tMTN", "iata_code": None, "icao_code": None, "tm": 1, "name": "Metronom"},
            {"code": "tNWB", "iata_code": None, "icao_code": None, "tm": 1, "name": "NordWestBahn"},
            {"code": "tVEO", "iata_code": None, "icao_code": None, "tm": 1, "name": "Veolia"},
            {"code": "tWST", "iata_code": '5W', "icao_code": None, "tm": 1, "name": "Westbahn"},
            {"code": "tWFB", "iata_code": None, "icao_code": None, "tm": 1, "name": "WestfalenBahn"},
            {"code": "tSEG", "iata_code": None, "icao_code": None, "tm": 1, "name": "SWEG"},

            #DK
            {"code": "tDSB", "iata_code": None, "icao_code": None, "tm": 1, "name": "DSB"},

            #ES
            {"code": "tRNF", "iata_code": '4R', "icao_code": None, "tm": 1, "name": "Renfe"},
            {"code": "tEUS", "iata_code": None, "icao_code": None, "tm": 1, "name": "Euskotren"},

            #FR
            {"code": "tOUI", "iata_code": '2C', "icao_code": None, "tm": 1, "name": "Oui SNCF"},
            {"code": "tTDV", "iata_code": None, "icao_code": None, "tm": 1, "name": "Transdev"},
            {"code": "tRHO", "iata_code": None, "icao_code": None, "tm": 1, "name": "Rhônexpress"},
            {"code": "tLYR", "iata_code": None, "icao_code": None, "tm": 1, "name": "TGV Lyria"},

            #FI
            {"code": "tVRF", "iata_code": None, "icao_code": None, "tm": 1, "name": "VR"},

            #HR
            {"code": "tHZP", "iata_code": None, "icao_code": None, "tm": 1, "name": "HZPP"},

            #HU
            {"code": "tMAV", "iata_code": None, "icao_code": None, "tm": 1, "name": "MÁV"},

            #IE
            {"code": "tCIE", "iata_code": None, "icao_code": None, "tm": 1, "name": "Irish Rail"},

            #IT
            {"code": "tTIT", "iata_code": '7T', "icao_code": None, "tm": 1, "name": "Trenitalia"},
            {"code": "tNRD", "iata_code": None, "icao_code": None, "tm": 1, "name": "Trenord"},
            {"code": "tNTV", "iata_code": None, "icao_code": None, "tm": 1, "name": "Italo"},
            {"code": "tTLO", "iata_code": None, "icao_code": None, "tm": 1, "name": "Thello"},

            #LU
            {"code": "tCFL", "iata_code": None, "icao_code": None, "tm": 1, "name": "CFL"},

            #NL
            {"code": "tARR", "iata_code": None, "icao_code": None, "tm": 1, "name": "Arriva"},
            {"code": "tKEO", "iata_code": None, "icao_code": None, "tm": 1, "name": "Eurobahn"},
            {"code": "tNSN", "iata_code": None, "icao_code": None, "tm": 1, "name": "NS"},
            {"code": "tNSI", "iata_code": None, "icao_code": None, "tm": 1, "name": "NS International"},

            #NO
            {"code": "tNSB", "iata_code": None, "icao_code": None, "tm": 1, "name": "NSB"},

            #PL
            {"code": "tPKP", "iata_code": None, "icao_code": None, "tm": 1, "name": "PKP Intercity"},
            {"code": "tPOL", "iata_code": None, "icao_code": None, "tm": 1, "name": "PolRegio"},

            #PT
            {"code": "tCPT", "iata_code": None, "icao_code": None, "tm": 1, "name": "Comboios de Portugal"},

            #UK
            {"code": "tAGA", "iata_code": None, "icao_code": None, "tm": 1, "name": "Abellio Greater Anglia"},
            {"code": "tATW", "iata_code": None, "icao_code": None, "tm": 1, "name": "Arriva Trains Wales"},
            {"code": "tCHR", "iata_code": None, "icao_code": None, "tm": 1, "name": "Chiltern Railways"},
            {"code": "tXCY", "iata_code": None, "icao_code": None, "tm": 1, "name": "CrossCountry"},
            {"code": "tEST", "iata_code": None, "icao_code": None, "tm": 1, "name": "East Coast"},
            {"code": "tEMT", "iata_code": None, "icao_code": None, "tm": 1, "name": "East Midlands Trains"},
            {"code": "tFHT", "iata_code": None, "icao_code": None, "tm": 1, "name": "First Hull Trains"},
            {"code": "tGWX", "iata_code": None, "icao_code": None, "tm": 1, "name": "Gatwick Express"},
            {"code": "tGNR", "iata_code": None, "icao_code": None, "tm": 1, "name": "Great Northern"},
            {"code": "tGWR", "iata_code": None, "icao_code": None, "tm": 1, "name": "Great Western Railway"},
            {"code": "tLMD", "iata_code": None, "icao_code": None, "tm": 1, "name": "London Midland"},
            {"code": "tLNE", "iata_code": None, "icao_code": None, "tm": 1, "name": "London North Eastern Railway"},
            {"code": "tNOT", "iata_code": None, "icao_code": None, "tm": 1, "name": "Northern"},
            {"code": "tSCS", "iata_code": None, "icao_code": None, "tm": 1, "name": "Serco Caledonian Sleeper"},
            {"code": "tSCR", "iata_code": None, "icao_code": None, "tm": 1, "name": "ScotRail"},
            {"code": "tSWT", "iata_code": None, "icao_code": None, "tm": 1, "name": "South West Trains"},
            {"code": "tSTN", "iata_code": None, "icao_code": None, "tm": 1, "name": "Southern"},
            {"code": "tTHL", "iata_code": None, "icao_code": None, "tm": 1, "name": "Thameslink"},
            {"code": "tTPE", "iata_code": None, "icao_code": None, "tm": 1, "name": "TransPennine Express"},
            {"code": "tVIR", "iata_code": None, "icao_code": None, "tm": 1, "name": "Virgin Trains"},
            {"code": "tGCR", "iata_code": None, "icao_code": None, "tm": 1, "name": "Grand Central Railway"},
            {"code": "tMGB", "iata_code": None, "icao_code": None, "tm": 1, "name": "Megabus train"},

            #RO
            {"code": "tCFR", "iata_code": '9G', "icao_code": None, "tm": 1, "name": "CFR"}, #Căile Ferate Române

            #RU
            {"code": "tOAO", "iata_code": '9G', "icao_code": None, "tm": 1, "name": "Russian Railways"},
            {"code": "tGXP", "iata_code": None, "icao_code": None, "tm": 1, "name": "Grand Express"},

            #SE
            {"code": "tSSJ", "iata_code": None, "icao_code": None, "tm": 1, "name": "SJ"},
            {"code": "tMTR", "iata_code": None, "icao_code": None, "tm": 1, "name": "MTR Express"},
            {"code": "tNRR", "iata_code": None, "icao_code": None, "tm": 1, "name": "Norrtåg"},
            {"code": "tKAB", "iata_code": None, "icao_code": None, "tm": 1, "name": "Tågkompaniet"},
            {"code": "tSTG", "iata_code": None, "icao_code": None, "tm": 1, "name": "Snälltåget"},
            {"code": "tLTK", "iata_code": None, "icao_code": None, "tm": 1, "name": "LT Kronoberg"},
            {"code": "tORE", "iata_code": None, "icao_code": None, "tm": 1, "name": "Öresundståg"},
            {"code": "tULT", "iata_code": None, "icao_code": None, "tm": 1, "name": "Public Traffic Uppland train"},

            #SI
            {"code": "tSIR", "iata_code": None, "icao_code": None, "tm": 1, "name": "SŽ"},

            #SK
            {"code": "tZSK", "iata_code": None, "icao_code": None, "tm": 1, "name": "ZSSK"},

            #TR
            {"code": "tOSE", "iata_code": None, "icao_code": None, "tm": 1, "name": "trainOSE"}, #Turkey

            #unknown
            {"code": "tXXX", "iata_code": None, "icao_code": None, "tm": 1, "name": ""},
        ]

        bus_carriers = [
            {"code": "bADY", "iata_code": None, "icao_code": None, "tm": 2, "name": "Adiyaman Güleras Turizm"},
            {"code": "bAGT", "iata_code": None, "icao_code": None, "tm": 2, "name": "Agat"},
            {"code": "bAGR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Agreda"},
            {"code": "bABN", "iata_code": None, "icao_code": None, "tm": 2, "name": "AerobusBCN"},
            {"code": "bAIR", "iata_code": None, "icao_code": None, "tm": 2, "name": "aircoach"},
            {"code": "bAIS", "iata_code": None, "icao_code": None, "tm": 2, "name": "Aisa"},
            {"code": "bAMB", "iata_code": None, "icao_code": None, "tm": 2, "name": "Almeria-Murcia Bus SL"},
            {"code": "bALS", "iata_code": None, "icao_code": None, "tm": 2, "name": "Alsa"},
            # {"code": "bALV", "iata_code": None, "icao_code": None, "tm": 2, "name": "Alava Bus"},
            {"code": "bAND", "iata_code": None, "icao_code": None, "tm": 2, "name": "Directbus"},
            {"code": "bANK", "iata_code": None, "icao_code": None, "tm": 2, "name": "Ankara As Turizm"},
            {"code": "bAVT", "iata_code": None, "icao_code": None, "tm": 2, "name": "Avtotranzit"},
            {"code": "bJMZ", "iata_code": None, "icao_code": None, "tm": 2, "name": "Autobuses Jimenez"},
            {"code": "bARD", "iata_code": None, "icao_code": None, "tm": 2, "name": "Arda Tur"},
            {"code": "bARR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Arriva"},
            {"code": "bARX", "iata_code": None, "icao_code": None, "tm": 2, "name": "Arriva Express"},
            {"code": "bAUT", "iata_code": None, "icao_code": None, "tm": 2, "name": "Autna"},
            {"code": "bAVZ", "iata_code": None, "icao_code": None, "tm": 2, "name": "Avanza"},
            {"code": "bAVX", "iata_code": None, "icao_code": None, "tm": 2, "name": "AVSA"},
            {"code": "bBKL", "iata_code": None, "icao_code": None, "tm": 2, "name": "Bakal S.V."},
            {"code": "bBAL", "iata_code": None, "icao_code": None, "tm": 2, "name": "Baltour"},
            {"code": "bBAM", "iata_code": None, "icao_code": None, "tm": 2, "name": "BAM Bus Almeria Madrid"},
            {"code": "bBKR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Becker Reisen"},
            {"code": "bBEN", "iata_code": None, "icao_code": None, "tm": 2, "name": "Ben Turizm"},
            {"code": "bBIL", "iata_code": None, "icao_code": None, "tm": 2, "name": "Bilmanbus"},
            {"code": "bBLA", "iata_code": None, "icao_code": None, "tm": 2, "name": "BlaBlaBus"},
            {"code": "bBZR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Bozur"},
            {"code": "bBSZ", "iata_code": None, "icao_code": None, "tm": 2, "name": "Brabusz"},
            {"code": "bPLN", "iata_code": None, "icao_code": None, "tm": 2, "name": "Busplana"},
            {"code": "bBUR", "iata_code": None, "icao_code": None, "tm": 2, "name": "La Burundesa"},
            {"code": "bDYR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Can Diyarbakır Turizm"},
            {"code": "bCAL", "iata_code": None, "icao_code": None, "tm": 2, "name": "Calecar-Intercar"},
            {"code": "bCAY", "iata_code": None, "icao_code": None, "tm": 2, "name": "Çayırağası Turizm"},
            {"code": "bCTI", "iata_code": None, "icao_code": None, "tm": 2, "name": "Citi Express"},
            {"code": "bCBX", "iata_code": None, "icao_code": None, "tm": 2, "name": "CitybusExpress"},
            # {"code": "bCBE", "iata_code": None, "icao_code": None, "tm": 2, "name": "CityBusExpress---"}, #to be deleted from March
            {"code": "bCLN", "iata_code": None, "icao_code": None, "tm": 2, "name": "Citylink"},
            {"code": "bCIZ", "iata_code": None, "icao_code": None, "tm": 2, "name": "Cizre Nuh İtimat"},
            {"code": "bCMS", "iata_code": None, "icao_code": None, "tm": 2, "name": "Comes"},
            {"code": "bCIA", "iata_code": None, "icao_code": None, "tm": 2, "name": "Cooperativa Interurbana Andorrana SA"},
            {"code": "bCKA", "iata_code": None, "icao_code": None, "tm": 2, "name": "Çorum Kargı Turizm"},
            {"code": "bCRJ", "iata_code": None, "icao_code": None, "tm": 2, "name": "Črnja Tours"},
            {"code": "bCSR", "iata_code": None, "icao_code": None, "tm": 2, "name": "CSr Seyahat"},
            {"code": "bCDR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Cuadrabus"},
            {"code": "bDAI", "iata_code": None, "icao_code": None, "tm": 2, "name": "Daibus-Interbus"},
            {"code": "bDCO", "iata_code": None, "icao_code": None, "tm": 2, "name": "Dainco"},
            {"code": "bDMS", "iata_code": None, "icao_code": None, "tm": 2, "name": "Damas"},
            {"code": "bDNB", "iata_code": None, "icao_code": None, "tm": 2, "name": "Deinbus"},
            {"code": "bDNY", "iata_code": None, "icao_code": None, "tm": 2, "name": "Denysivka-Plus"},
            {"code": "bDMD", "iata_code": None, "icao_code": None, "tm": 2, "name": "D.M.D. Ukrayina / Д.М.Д. УКРАЇНА"},
            {"code": "bECL", "iata_code": None, "icao_code": None, "tm": 2, "name": "Ecolines"},
            {"code": "bEFR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Efremeniuk A.L."},
            {"code": "bEST", "iata_code": None, "icao_code": None, "tm": 2, "name": "Est-Lorek"},
            {"code": "bERB", "iata_code": None, "icao_code": None, "tm": 2, "name": "Eurobus"},
            {"code": "bEUR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Eurolines"},
            {"code": "bERP", "iata_code": None, "icao_code": None, "tm": 2, "name": "Europabus"},
            {"code": "bEVA", "iata_code": None, "icao_code": None, "tm": 2, "name": "EVA"},
            {"code": "bFLX", "iata_code": None, "icao_code": None, "tm": 2, "name": "Flixbus"},
            {"code": "bFOP", "iata_code": None, "icao_code": None, "tm": 2, "name": "Fop Yatsiv"},
            {"code": "bFME", "iata_code": None, "icao_code": None, "tm": 2, "name": "Follow me!"},
            {"code": "bGAL", "iata_code": None, "icao_code": None, "tm": 2, "name": "Gal-Vsevit"},
            {"code": "bGOB", "iata_code": None, "icao_code": None, "tm": 2, "name": "Gobus"},
            {"code": "bGLN", "iata_code": None, "icao_code": None, "tm": 2, "name": "Gülen Turizm"},
            {"code": "bGUL", "iata_code": None, "icao_code": None, "tm": 2, "name": "Gülnarlılar Mersin Nur Turizm"},
            {"code": "bHAS", "iata_code": None, "icao_code": None, "tm": 2, "name": "Has Turizm A.Ş."},
            {"code": "bHSY", "iata_code": None, "icao_code": None, "tm": 2, "name": "Hassoy Turizm"},
            {"code": "bHTY", "iata_code": None, "icao_code": None, "tm": 2, "name": "Hatay Nur Seyahat"},
            {"code": "bHIF", "iata_code": None, "icao_code": None, "tm": 2, "name": "Hife"},
            {"code": "bIBE", "iata_code": None, "icao_code": None, "tm": 2, "name": "Iberia"}, #usually operated by Alsa. Used at least when parsing EBKR
            {"code": "bICB", "iata_code": None, "icao_code": None, "tm": 2, "name": "IC Bus"},
            {"code": "bITK", "iata_code": None, "icao_code": None, "tm": 2, "name": "Intaks"},
            {"code": "bBJZ", "iata_code": None, "icao_code": None, "tm": 2, "name": "Interbus Badajoz"},
            {"code": "bIRB", "iata_code": None, "icao_code": None, "tm": 2, "name": "IRB"},
            {"code": "bISI", "iata_code": None, "icao_code": None, "tm": 2, "name": "Isilines"},
            {"code": "bJTZ", "iata_code": None, "icao_code": None, "tm": 2, "name": "Jet Turizm"},
            {"code": "bJOR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Jordan Group"},
            {"code": "bJDO", "iata_code": None, "icao_code": None, "tm": 2, "name": "Jimenez Dorado Autocares"},
            {"code": "bKOR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Korona Travel"},
            {"code": "bKRI", "iata_code": None, "icao_code": None, "tm": 2, "name": "Krivoshapka LI / Кривошапка Л.І."},
            {"code": "bSPV", "iata_code": None, "icao_code": None, "tm": 2, "name": "La Sepulvedana"},
            {"code": "bLAZ", "iata_code": None, "icao_code": None, "tm": 2, "name": "Autocares Lázara"},
            {"code": "bLEO", "iata_code": None, "icao_code": None, "tm": 2, "name": "Leo Express"},
            {"code": "bLDA", "iata_code": None, "icao_code": None, "tm": 2, "name": "Leda"},
            {"code": "bLID", "iata_code": None, "icao_code": None, "tm": 2, "name": "Lider Elbistan"},
            {"code": "bLRA", "iata_code": None, "icao_code": None, "tm": 2, "name": "Líneas Regulares de Álava"},
            {"code": "bLYC", "iata_code": None, "icao_code": None, "tm": 2, "name": "Lycar"},
            {"code": "bMGS", "iata_code": None, "icao_code": None, "tm": 2, "name": "Magical Shuttle"},
            {"code": "bDLM", "iata_code": None, "icao_code": None, "tm": 2, "name": "Mardin Dilmenler Turizm"},
            {"code": "bSEY", "iata_code": None, "icao_code": None, "tm": 2, "name": "Mardin Seyahat"},
            {"code": "bMAR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Marino Bus"},
            {"code": "bMRS", "iata_code": None, "icao_code": None, "tm": 2, "name": "Mersin Travel Turizm"},
            {"code": "bMTR", "iata_code": None, "icao_code": None, "tm": 2, "name": "METRO"},
            {"code": "bMYT", "iata_code": None, "icao_code": None, "tm": 2, "name": "Midyat Southeast Travel"},
            {"code": "bMHL", "iata_code": None, "icao_code": None, "tm": 2, "name": "Mihaljevic Bus"},
            {"code": "bMNB", "iata_code": None, "icao_code": None, "tm": 2, "name": "Monbus"},
            {"code": "bMTZ", "iata_code": None, "icao_code": None, "tm": 2, "name": "Matuszek"},
            {"code": "bNMG", "iata_code": None, "icao_code": None, "tm": 2, "name": "Nomago"},
            {"code": "bNXP", "iata_code": None, "icao_code": None, "tm": 2, "name": "National Express"},
            {"code": "bOKB", "iata_code": None, "icao_code": None, "tm": 2, "name": "OKbus"},
            {"code": "bOMG", "iata_code": None, "icao_code": None, "tm": 2, "name": "Omega Group"},
            {"code": "bONC", "iata_code": None, "icao_code": None, "tm": 2, "name": "Öncü Seyahat"},
            {"code": "bORL", "iata_code": None, "icao_code": None, "tm": 2, "name": "Orlan"},
            {"code": "bOUI", "iata_code": None, "icao_code": None, "tm": 2, "name": "Ouibus"},
            {"code": "bOZL", "iata_code": None, "icao_code": None, "tm": 2, "name": "Özlem Cizre Nuh"},
            {"code": "bPKS", "iata_code": None, "icao_code": None, "tm": 2, "name": "PKS Szczecin"},
            {"code": "bPLM", "iata_code": None, "icao_code": None, "tm": 2, "name": "PLM Autocares"},
            {"code": "bPNK", "iata_code": None, "icao_code": None, "tm": 2, "name": "Pinkbus"},
            {"code": "bREX", "iata_code": None, "icao_code": None, "tm": 2, "name": "Rede expressos"},
            {"code": "bRNX", "iata_code": None, "icao_code": None, "tm": 2, "name": "RENEX"},
            {"code": "bRJT", "iata_code": None, "icao_code": None, "tm": 2, "name": "RegioJet"},
            {"code": "bRHT", "iata_code": None, "icao_code": None, "tm": 2, "name": "RH Turizm"},
            {"code": "bROC", "iata_code": None, "icao_code": None, "tm": 2, "name": "Roca Travelino"},
            {"code": "bSAI", "iata_code": None, "icao_code": None, "tm": 2, "name": "Saiz Tour"},
            {"code": "bSAM", "iata_code": None, "icao_code": None, "tm": 2, "name": "Grupo Samar"},
            {"code": "bSNL", "iata_code": None, "icao_code": None, "tm": 2, "name": "Şanal Turizm"},
            {"code": "bSCO", "iata_code": None, "icao_code": None, "tm": 2, "name": "Secorbus"},
            {"code": "bSES", "iata_code": None, "icao_code": None, "tm": 2, "name": "Ses Turizm"},
            {"code": "bSFP", "iata_code": None, "icao_code": None, "tm": 2, "name": "Sfera Platinun"},
            {"code": "bSIN", "iata_code": None, "icao_code": None, "tm": 2, "name": "Sindbad Eurobus"},
            {"code": "bSLK", "iata_code": None, "icao_code": None, "tm": 2, "name": "Selcuk Turizm"},
            {"code": "bSVK", "iata_code": None, "icao_code": None, "tm": 2, "name": "Slovak Lines"},
            {"code": "bSCB", "iata_code": None, "icao_code": None, "tm": 2, "name": "Socibus"},
            {"code": "bBTM", "iata_code": None, "icao_code": None, "tm": 2, "name": "Star Batman"},
            {"code": "bDYB", "iata_code": None, "icao_code": None, "tm": 2, "name": "Star Diyarbakir"},
            {"code": "bMRD", "iata_code": None, "icao_code": None, "tm": 2, "name": "Star Mardin Turizm"},
            {"code": "bSVD", "iata_code": None, "icao_code": None, "tm": 2, "name": "SVD Trans"},
            {"code": "bTRR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Terravision"},
            {"code": "bTHP", "iata_code": None, "icao_code": None, "tm": 2, "name": "Therpasa"},
            {"code": "bTME", "iata_code": None, "icao_code": None, "tm": 2, "name": "Tiemme SpA"},
            {"code": "bTOK", "iata_code": None, "icao_code": None, "tm": 2, "name": "TOKS"},
            {"code": "bTSH", "iata_code": None, "icao_code": None, "tm": 2, "name": "Tourist Service Holding"},
            {"code": "bTOV", "iata_code": None, "icao_code": None, "tm": 2, "name": "TOV Nasorokh"},
            {"code": "bTEU", "iata_code": None, "icao_code": None, "tm": 2, "name": "Trans Europa"},
            {"code": "bTTT", "iata_code": None, "icao_code": None, "tm": 2, "name": "Trans Tempo / ТрансТемпо"},
            {"code": "bTRN", "iata_code": None, "icao_code": None, "tm": 2, "name": "Turancar"},
            {"code": "bULU", "iata_code": None, "icao_code": None, "tm": 2, "name": "Ulusoy Seyahat"},
            {"code": "bIVK", "iata_code": None, "icao_code": None, "tm": 2, "name": "Union Ivkoni"},
            {"code": "bUNN", "iata_code": None, "icao_code": None, "tm": 2, "name": "La Union"},
            {"code": "bVKV", "iata_code": None, "icao_code": None, "tm": 2, "name": "Vasilkiv Trans Avto"},
            {"code": "bVBS", "iata_code": None, "icao_code": None, "tm": 2, "name": "Vibasa"},
            {"code": "bVLR", "iata_code": None, "icao_code": None, "tm": 2, "name": "Vilartrans"},
            {"code": "bVCK", "iata_code": None, "icao_code": None, "tm": 2, "name": "Vincek Autobusi"},
            {"code": "bVST", "iata_code": None, "icao_code": None, "tm": 2, "name": "Visit-Tour"},
            {"code": "bVIT", "iata_code": None, "icao_code": None, "tm": 2, "name": "Vital Euro Trans"},
            {"code": "bVOV", "iata_code": None, "icao_code": None, "tm": 2, "name": "VOVA AD/Kurylovich"},
            {"code": "bVYG", "iata_code": None, "icao_code": None, "tm": 2, "name": "Voyager Transport"},
            {"code": "bYAS", "iata_code": None, "icao_code": None, "tm": 2, "name": "Yeni Aksaray Seyahat"},
            {"code": "bYUK", "iata_code": None, "icao_code": None, "tm": 2, "name": "Yükseller Aksaray Birlik"},
            {"code": "bZSA", "iata_code": None, "icao_code": None, "tm": 2, "name": "Zamora Salamanca"},

            {"code": "bBCT", "iata_code": None, "icao_code": None, "tm": 2, "name": "Buscenter"},

            {"code": "bB4U", "iata_code": None, "icao_code": None, "tm": 2, "name": "Bus4You"},
            {"code": "bNTX", "iata_code": None, "icao_code": None, "tm": 2, "name": "Nettbus Express"},
            {"code": "bFLC", "iata_code": None, "icao_code": None, "tm": 2, "name": "Flibco"},
            {"code": "bTOU", "iata_code": None, "icao_code": None, "tm": 2, "name": "Touring"},
            {"code": "bONE", "iata_code": None, "icao_code": None, "tm": 2, "name": "Onebus"},
            {"code": "bMGB", "iata_code": None, "icao_code": None, "tm": 2, "name": "Megabus"},
            {"code": "bSGL", "iata_code": None, "icao_code": None, "tm": 2, "name": "Sagales"},
            {"code": "bTEI", "iata_code": None, "icao_code": None, "tm": 2, "name": "Teisa"},
            {"code": "bONN", "iata_code": None, "icao_code": None, "tm": 2, "name": "Onnibus"},
            {"code": "bSWX", "iata_code": None, "icao_code": None, "tm": 2, "name": "Swiss Express"},
            # {"code": "???", "iata_code": None, "icao_code": None, "tm": 2, "name": "Orange Ways"},
            # {"code": "???", "iata_code": None, "icao_code": None, "tm": 2, "name": "CityBus Express"},

            #unknown
            {"code": "bXXX", "iata_code": None, "icao_code": None, "tm": 2, "name": ""},
        ]

        car_carriers = [
            {"code": "BLA", "iata_code": None, "icao_code": None, "tm": 3, "name": "Blablacar"},
            {"code": "BSH", "iata_code": None, "icao_code": None, "tm": 3, "name": "Berlin Shuttle"},
        ]

        ferry_carriers = [
            {"code": "ISC", "iata_code": None, "icao_code": None, "tm": 4, "name": "Iscomar"},
            {"code": "BAL", "iata_code": None, "icao_code": None, "tm": 4, "name": "Balearia"},
            {"code": "TMD", "iata_code": None, "icao_code": None, "tm": 4, "name": "Trasmediterranea"},
        ]
