# Regions of some European countries

        # region iso codes used: https://en.wikipedia.org/wiki/ISO_3166-1
        # https://en.wikipedia.org/wiki/ISO_3166-2:DE
        # https://en.wikipedia.org/wiki/ISO_3166-2:ES
        # https://en.wikipedia.org/wiki/ISO_3166-2:PT

        regions = [
            {"iso_code": "DE-BW", "name": "Baden-Wuerttemberg"},
            {"iso_code": "DE-BY", "name": "Bayern"},
            {"iso_code": "DE-BE", "name": "Berlin"},
            {"iso_code": "DE-BB", "name": "Brandenburg"},
            {"iso_code": "DE-HB", "name": "Bremen"},
            {"iso_code": "DE-HH", "name": "Hamburg"},
            {"iso_code": "DE-HE", "name": "Hesse"},
            {"iso_code": "DE-MV", "name": "Mecklenburg-Vorpommern"},
            {"iso_code": "DE-NI", "name": "Niedersachsen"},
            {"iso_code": "DE-NW", "name": "Nordrhein-Westfalen"},
            {"iso_code": "DE-RP", "name": "Rheinland-Pfalz"},
            {"iso_code": "DE-SL", "name": "Saarland"},
            {"iso_code": "DE-SN", "name": "Sachsen"},
            {"iso_code": "DE-ST", "name": "Sachsen-Anhalt"},
            {"iso_code": "DE-SH", "name": "Schleswig-Holstein"},
            {"iso_code": "DE-TH", "name": "Thueringen"},

            {"iso_code": "ES-AN", "name": "Andalucia"},
            {"iso_code": "ES-AR", "name": "Aragon"},
            {"iso_code": "ES-AS", "name": "Asturias"},
            {"iso_code": "ES-CN", "name": "Canarias"},
            {"iso_code": "ES-CB", "name": "Cantabria"},
            {"iso_code": "ES-CM", "name": "Castilla-La Mancha"},
            {"iso_code": "ES-CL", "name": "Castilla y Leon"},
            {"iso_code": "ES-CT", "name": "Catalunya"},
            {"iso_code": "ES-EX", "name": "Extremadura"},
            {"iso_code": "ES-GA", "name": "Galicia"},
            {"iso_code": "ES-IB", "name": "Islas Baleares"},
            {"iso_code": "ES-RI", "name": "La Rioja"},
            {"iso_code": "ES-MD", "name": "Comunidad de Madrid"},
            {"iso_code": "ES-MC", "name": "Region de Murcia"},
            {"iso_code": "ES-NC", "name": "Navarra"},
            {"iso_code": "ES-PV", "name": "Pais Vasco"},
            {"iso_code": "ES-VC", "name": "Comunidad Valenciana"},
            {"iso_code": "ES-CE", "name": "Ceuta"},
            {"iso_code": "ES-ML", "name": "Melilla"},

            {"iso_code": "PT-01", "name": "Aveiro"},
            {"iso_code": "PT-02", "name": "Beja"},
            {"iso_code": "PT-03", "name": "Braga"},
            {"iso_code": "PT-04", "name": "Bragança"},
            {"iso_code": "PT-05", "name": "Castelo Branco"},
            {"iso_code": "PT-06", "name": "Coimbra"},
            {"iso_code": "PT-07", "name": "Évora"},
            {"iso_code": "PT-08", "name": "Faro"},
            {"iso_code": "PT-09", "name": "Guarda"},
            {"iso_code": "PT-10", "name": "Leira"},
            {"iso_code": "PT-11", "name": "Lisboa"},
            {"iso_code": "PT-12", "name": "Portalegre"},
            {"iso_code": "PT-13", "name": "Porto"},
            {"iso_code": "PT-14", "name": "Santarém"},
            {"iso_code": "PT-15", "name": "Setúbal"},
            {"iso_code": "PT-16", "name": "Viana de Costelo"},
            {"iso_code": "PT-17", "name": "Vila Real"},
            {"iso_code": "PT-18", "name": "Viseu"},
            {"iso_code": "PT-20", "name": "Açores"},
            {"iso_code": "PT-30", "name": "Madeira"},
        ]
